# product = Product.new(name: "Duck Magnet", price: 0.50, image_url: "TBD", desription: "magnet in shape of a duck")
# product = Product.new(name: "Turtle Magnet", price: 0.50, image_url: "TBD", desription: "magnet in shape of a turtle")
# product = Product.create(name: "Apple Magnet", price: 0.50, image_url: "TBD", desription: "magnet in shape of a Apple")
# product = Product.create(name: "Star Magnet", price: 0.50, image_url: "TBD", desription: "magnet in shape of a Star")
# product = Product.create(name: "Butterfly Magnet", price: 0.50, image_url: "TBD", desription: "magnet in shape of a Butterfly")
